name: Build and deploy Node.js app to Azure Web App - shea-prisma-test-001

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://mentra.azurecr.io/
          username: ${{ secrets.CONTAINER_USERNAME }}
          password: ${{ secrets.CONTAINER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mentra.azurecr.io/${{ secrets.CONTAINER_USERNAME }}/shea_prisma_test:${{ github.sha }}
          file: ./dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'staging'
      # Cannot use secrets here (https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idenvironment)
      url: 'https://shea-prisma-test-001.azurewebsites.net/'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'shea-prisma-test-001'
        images: 'mentra.azurecr.io/${{ secrets.CONTAINER_USERNAME }}/shea_prisma_test:${{ github.sha }}'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9B704A6BB3AE495381144302D03ACF1B }}
        slot-name: 'production'